export const PRODUCT_LIST_RQUEST  = 'PRODUCT_LIST_RQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL    = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_RQUEST  = 'PRODUCT_DETAILS_RQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL    = 'PRODUCT_DETAILS_FAIL'
